name: deploy-arm-template

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_RESOURCE_GROUP_NAME: azurebrains-rg

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: whiteducksoftware/azure-arm-action@v3.2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
        templateLocation: virtualMachine/azuredeploy.json
        parameters: virtualMachine/azuredeploy.parameters.json
        deploymentName: azurebrains-github-actions
        overrideParameters: |
          adminPassword=${{ secrets.ADMIN_PASSWORD }}
